artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/aa3a623eb98a43f5bb0f1f6563fd9064/artifacts
end_time: 1778513388987
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: aa3a623eb98a43f5bb0f1f6563fd9064
run_name: monitoring_outliers
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513388976
status: 3
tags: []
user_id: bioinf
