artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/e3d0fd942f734e2bbf73600478c098bf/artifacts
end_time: 1778513444120
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: e3d0fd942f734e2bbf73600478c098bf
run_name: day_5
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513444115
status: 3
tags: []
user_id: bioinf
