creation_timestamp: 1778513443627
current_stage: Staging
deployment_job_state: null
description: null
last_updated_timestamp: 1778513443641
model_id: m-997eb34e55b7487887e78fdd42a8eb23
name: breast_cancer_classifier
run_id: 0b07c2aa830140c6bd3325e0f047b9b2
run_link: null
source: models:/m-997eb34e55b7487887e78fdd42a8eb23
status: READY
status_message: null
storage_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/models/m-997eb34e55b7487887e78fdd42a8eb23/artifacts
user_id: null
version: 5
workspace: default
