artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/bebbb355031f4549afd106ad6b35cec7/artifacts
end_time: 1778513403676
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: bebbb355031f4549afd106ad6b35cec7
run_name: monitoring_outliers
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513403656
status: 3
tags: []
user_id: bioinf
