artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/1ddea9b5142141579b94c66158ac9ab2/artifacts
end_time: 1778513233431
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 1ddea9b5142141579b94c66158ac9ab2
run_name: monitoring_noise_low
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513233405
status: 3
tags: []
user_id: bioinf
