artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/422b50981b634c248828cea42fb0b40d/artifacts
end_time: 1778513201110
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 422b50981b634c248828cea42fb0b40d
run_name: monitoring_bias
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513201092
status: 3
tags: []
user_id: bioinf
