artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/b10dba1a153642c195e894d5a17ef957/artifacts
end_time: 1778586927720
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: b10dba1a153642c195e894d5a17ef957
run_name: monitoring_noise_high
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586927704
status: 3
tags: []
user_id: bioinf
