artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/867a204ee9fd405fb9136df846187467/artifacts
end_time: 1778513444107
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: 867a204ee9fd405fb9136df846187467
run_name: day_4
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513444101
status: 3
tags: []
user_id: bioinf
