artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/76673545d39a4648b5065e1adf6b6c70/artifacts
end_time: 1778513198629
entry_point_name: ''
experiment_id: '446589208299238719'
lifecycle_stage: active
run_id: 76673545d39a4648b5065e1adf6b6c70
run_name: tasteful-mouse-726
source_name: ''
source_type: 4
source_version: ''
start_time: 1778512737821
status: 3
tags: []
user_id: bioinf
