creation_timestamp: 1778512738185
current_stage: Archived
deployment_job_state: null
description: null
last_updated_timestamp: 1778588190139
model_id: m-f4545d0b74674266a20acccf3efddf5c
name: breast_cancer_classifier
run_id: 12e790fc65c34690b0f2afb0629bad7e
run_link: null
source: models:/m-f4545d0b74674266a20acccf3efddf5c
status: READY
status_message: null
storage_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/models/m-f4545d0b74674266a20acccf3efddf5c/artifacts
user_id: null
version: 2
workspace: default
