artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/2c0e475891b84d1d9c8c990ac46662c7/artifacts
end_time: 1778513201091
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 2c0e475891b84d1d9c8c990ac46662c7
run_name: monitoring_outliers
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513201076
status: 3
tags: []
user_id: bioinf
