artifact_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621
creation_time: 1778513444044
experiment_id: '220729347377670621'
last_update_time: 1778513444044
lifecycle_stage: active
name: breast_cancer_06_daily_monitoring
trace_location: null
workspace: default
