artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/651012c484a04dd0b77ce5a3f652c659/artifacts
end_time: 1778513444094
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: 651012c484a04dd0b77ce5a3f652c659
run_name: day_3
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513444089
status: 3
tags: []
user_id: bioinf
