artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/fd3efbcd6408477998d502a563211680/artifacts
end_time: 1778513388997
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: fd3efbcd6408477998d502a563211680
run_name: monitoring_bias
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513388989
status: 3
tags: []
user_id: bioinf
