artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/d3d611433c00445789f70728de930d8d/artifacts
end_time: 1778512735410
entry_point_name: ''
experiment_id: '446589208299238719'
lifecycle_stage: active
run_id: d3d611433c00445789f70728de930d8d
run_name: XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1778512732942
status: 3
tags: []
user_id: bioinf
