artifact_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713
creation_time: 1778512738464
experiment_id: '591164253199477713'
last_update_time: 1778512738464
lifecycle_stage: active
name: breast_cancer_06_monitoring
trace_location: null
workspace: default
