creation_timestamp: 1778512738173
current_stage: Archived
deployment_job_state: null
description: null
last_updated_timestamp: 1778588190168
model_id: m-8f090381caf1415f8102b8d49812a9f3
name: breast_cancer_classifier
run_id: c0f6fdb88b3e4511a0c8ba2615c0d4d4
run_link: null
source: models:/m-8f090381caf1415f8102b8d49812a9f3
status: READY
status_message: null
storage_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/models/m-8f090381caf1415f8102b8d49812a9f3/artifacts
user_id: null
version: 1
workspace: default
