artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/465994246a9d4956ba4f02f3bdfbcbcb/artifacts
end_time: 1778588266309
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: 465994246a9d4956ba4f02f3bdfbcbcb
run_name: day_5
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588266303
status: 3
tags: []
user_id: bioinf
