artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/58e3b32013fe48c79557a70f2af5d3ac/artifacts
end_time: 1778588257774
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 58e3b32013fe48c79557a70f2af5d3ac
run_name: monitoring_noise_low
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588257754
status: 3
tags: []
user_id: bioinf
