artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/6c94c08ef2034b83a9f6e2d5f47302f8/artifacts
end_time: 1778513388937
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 6c94c08ef2034b83a9f6e2d5f47302f8
run_name: monitoring_missing_light
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513388926
status: 3
tags: []
user_id: bioinf
