creation_timestamp: 1778586878844
current_stage: Archived
deployment_job_state: null
description: null
last_updated_timestamp: 1778588190197
model_id: m-47f5e3328eaa42d5938f05b6a7b16dca
name: breast_cancer_classifier
run_id: 67511e553e0544539f99cce343941845
run_link: null
source: models:/m-47f5e3328eaa42d5938f05b6a7b16dca
status: READY
status_message: null
storage_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/models/m-47f5e3328eaa42d5938f05b6a7b16dca/artifacts
user_id: null
version: 6
workspace: default
