artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/251ecf54c48c4c89979e9eee008987ee/artifacts
end_time: 1778588266258
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: 251ecf54c48c4c89979e9eee008987ee
run_name: day_2
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588266250
status: 3
tags: []
user_id: bioinf
