artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/0391362e217b4f648780c1d4c6c36bd3/artifacts
end_time: 1778513201041
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 0391362e217b4f648780c1d4c6c36bd3
run_name: monitoring_missing_heavy
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513201022
status: 3
tags: []
user_id: bioinf
