artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/87c53ae445b5470fb52f4d58bd1820db/artifacts
end_time: 1778586939840
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: 87c53ae445b5470fb52f4d58bd1820db
run_name: day_4
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586939834
status: 3
tags: []
user_id: bioinf
