artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/a41253c0b4d14b3992f95df311dc6e60/artifacts
end_time: 1778588266276
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: a41253c0b4d14b3992f95df311dc6e60
run_name: day_3
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588266270
status: 3
tags: []
user_id: bioinf
