artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/1fe8df7663e24917b2f4f78fc85c605f/artifacts
end_time: 1778586939328
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 1fe8df7663e24917b2f4f78fc85c605f
run_name: Challenger_XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586937414
status: 3
tags: []
user_id: bioinf
