artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/aaeb8d81bb20490e832dab8f97aeb106/artifacts
end_time: 1778588257795
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: aaeb8d81bb20490e832dab8f97aeb106
run_name: monitoring_noise_high
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588257775
status: 3
tags: []
user_id: bioinf
