artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/97842bc7d134422bb9e0595aa484e206/artifacts
end_time: 1778588257817
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 97842bc7d134422bb9e0595aa484e206
run_name: monitoring_outliers
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588257796
status: 3
tags: []
user_id: bioinf
