artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/e89b7575253c4e2182f4f5e5c4a8fd1a/artifacts
end_time: 1778588257732
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: e89b7575253c4e2182f4f5e5c4a8fd1a
run_name: monitoring_missing_light
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588257713
status: 3
tags: []
user_id: bioinf
