artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/f6e73d68b62a4962afc85985882626df/artifacts
end_time: 1778586939827
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: f6e73d68b62a4962afc85985882626df
run_name: day_3
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586939822
status: 3
tags: []
user_id: bioinf
