artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/00307f942dc744c68423d313d223ee09/artifacts
end_time: 1778588257836
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 00307f942dc744c68423d313d223ee09
run_name: monitoring_bias
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588257818
status: 3
tags: []
user_id: bioinf
