artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/8cad8ae82b1c444599f00db7af67e5ae/artifacts
end_time: 1778586927669
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 8cad8ae82b1c444599f00db7af67e5ae
run_name: monitoring_missing_light
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586927651
status: 3
tags: []
user_id: bioinf
