artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/8244c11717124aed86dc2e692406d3a9/artifacts
end_time: 1778586925868
entry_point_name: ''
experiment_id: '446589208299238719'
lifecycle_stage: active
run_id: 8244c11717124aed86dc2e692406d3a9
run_name: wise-lynx-224
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586878459
status: 3
tags: []
user_id: bioinf
