artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/bba521e555ad4e1cbc2f48965d6137ac/artifacts
end_time: 1778513403636
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: bba521e555ad4e1cbc2f48965d6137ac
run_name: monitoring_noise_low
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513403617
status: 3
tags: []
user_id: bioinf
