artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/8c5b1418474a4e6e8961a6ef61ee1bbb/artifacts
end_time: 1778586876526
entry_point_name: ''
experiment_id: '446589208299238719'
lifecycle_stage: active
run_id: 8c5b1418474a4e6e8961a6ef61ee1bbb
run_name: XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586874552
status: 3
tags: []
user_id: bioinf
