artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/7f995f04cbe14916a1fcc6aa3d338988/artifacts
end_time: 1778586939856
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: 7f995f04cbe14916a1fcc6aa3d338988
run_name: day_5
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586939849
status: 3
tags: []
user_id: bioinf
