artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/9c68961352754ba4aeea7c2df62a02e2/artifacts
end_time: 1778588265756
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: 9c68961352754ba4aeea7c2df62a02e2
run_name: Challenger_XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588263884
status: 3
tags: []
user_id: bioinf
