creation_timestamp: 1778588189838
current_stage: Archived
deployment_job_state: null
description: null
last_updated_timestamp: 1778588190091
model_id: m-e4f3799e001842fb8d3da56a240e6879
name: breast_cancer_classifier
run_id: 1905b956efc74cff8df91f5f24a66b15
run_link: null
source: models:/m-e4f3799e001842fb8d3da56a240e6879
status: READY
status_message: null
storage_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/models/m-e4f3799e001842fb8d3da56a240e6879/artifacts
user_id: null
version: 12
workspace: default
