artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/e3a6d8453c0840c5a314de133d590bc2/artifacts
end_time: 1778588256024
entry_point_name: ''
experiment_id: '446589208299238719'
lifecycle_stage: active
run_id: e3a6d8453c0840c5a314de133d590bc2
run_name: aged-goat-158
source_name: ''
source_type: 4
source_version: ''
start_time: 1778588189275
status: 3
tags: []
user_id: bioinf
