artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/e3b298d43598464fb21fe1b483afdd44/artifacts
end_time: 1778513444061
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: e3b298d43598464fb21fe1b483afdd44
run_name: day_1
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513444055
status: 3
tags: []
user_id: bioinf
