artifact_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719
creation_time: 1778512726938
experiment_id: '446589208299238719'
last_update_time: 1778512726938
lifecycle_stage: active
name: breast_cancer_06_registry
trace_location: null
workspace: default
