artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/61479fc1809a4ca083b68fab77b32236/artifacts
end_time: 1778512737820
entry_point_name: ''
experiment_id: '446589208299238719'
lifecycle_stage: active
run_id: 61479fc1809a4ca083b68fab77b32236
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1778512735438
status: 3
tags: []
user_id: bioinf
