creation_timestamp: 1778588189938
current_stage: Production
deployment_job_state: null
description: null
last_updated_timestamp: 1778588190007
model_id: m-6065483262124847bfa32830498b75e3
name: breast_cancer_classifier
run_id: b00adc24365f4f3fa6531abdd7a171ff
run_link: null
source: models:/m-6065483262124847bfa32830498b75e3
status: READY
status_message: null
storage_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/models/m-6065483262124847bfa32830498b75e3/artifacts
user_id: null
version: 14
workspace: default
