artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/a37fe7c973a54b01b4f9f87cbe9008c8/artifacts
end_time: 1778586927687
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: a37fe7c973a54b01b4f9f87cbe9008c8
run_name: monitoring_missing_heavy
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586927670
status: 3
tags: []
user_id: bioinf
