artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/446589208299238719/12e790fc65c34690b0f2afb0629bad7e/artifacts
end_time: 1778512732259
entry_point_name: ''
experiment_id: '446589208299238719'
lifecycle_stage: active
run_id: 12e790fc65c34690b0f2afb0629bad7e
run_name: RandomForest
source_name: ''
source_type: 4
source_version: ''
start_time: 1778512729860
status: 3
tags: []
user_id: bioinf
