artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/bab9b237c5314d42a9394021d8166769/artifacts
end_time: 1778513389032
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: bab9b237c5314d42a9394021d8166769
run_name: monitoring_schema_drift
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513388999
status: 3
tags: []
user_id: bioinf
