artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/5d8a6015f45b4735a3315d7602e5bafc/artifacts
end_time: 1778513444079
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: 5d8a6015f45b4735a3315d7602e5bafc
run_name: day_2
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513444072
status: 3
tags: []
user_id: bioinf
