artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/a309b172d3444a8086873bdaadf2fdb6/artifacts
end_time: 1778513233509
entry_point_name: ''
experiment_id: '591164253199477713'
lifecycle_stage: active
run_id: a309b172d3444a8086873bdaadf2fdb6
run_name: monitoring_schema_drift
source_name: ''
source_type: 4
source_version: ''
start_time: 1778513233503
status: 3
tags: []
user_id: bioinf
