artifact_uri: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/220729347377670621/7786d37118df4826bc5d310f5b71132a/artifacts
end_time: 1778586939805
entry_point_name: ''
experiment_id: '220729347377670621'
lifecycle_stage: active
run_id: 7786d37118df4826bc5d310f5b71132a
run_name: day_2
source_name: ''
source_type: 4
source_version: ''
start_time: 1778586939800
status: 3
tags: []
user_id: bioinf
