creation_timestamp: 1778588265770
current_stage: Staging
deployment_job_state: null
description: null
last_updated_timestamp: 1778588265800
model_id: m-09c23039749f4a53a0f901a63a2af586
name: breast_cancer_classifier
run_id: 9c68961352754ba4aeea7c2df62a02e2
run_link: null
source: models:/m-09c23039749f4a53a0f901a63a2af586
status: READY
status_message: null
storage_location: /home/bioinf/Desktop/PERSONAL_WORK/RUMOS/MLengi/hidden_projet/breast_cancer_copy/mlflow_artifacts/591164253199477713/models/m-09c23039749f4a53a0f901a63a2af586/artifacts
user_id: null
version: 15
workspace: default
